Suppress 'CAM' compilation unless explicitly enabled
Either g++ version 7 or the iostream headers it ships with complain about ambiguous
overloads when the live version of cam.h's 'StreamCapture' is compiled.  Here's one
of the error sequences that results:

**********************
  In file included from ../kernel/V_VCamLog.cpp:27:0:
  ../kernel/cam.h: In member function ‘void CAM::Operation::associateParent(const string&, const string&)’:
  ../kernel/cam.h:261:13: error: ambiguous overload for ‘operator<<’ (operand types are ‘StreamCapture’ and ‘const char [18]’)
           StreamCapture()
           ~~~~~~~~~~~~~~~
             << "associateParentId" << parentId
             ^~~~~~~~~~~~~~~~~~~~~~
  ../kernel/cam.h:57:42: note: candidate: StreamCapture& StreamCapture::operator<<(const T&) [with T = char [18]]
     template <typename T> StreamCapture& operator<<(const T& rhs) {
                                          ^~~~~~~~
  In file included from /usr/include/c++/7/iostream:39:0,
                   from ../kernel/cam.h:10,
                   from ../kernel/V_VCamLog.cpp:27:
  /usr/include/c++/7/ostream:682:5: note: candidate: typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = StreamCapture; _Tp = char [18]; typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type = std::basic_ostream<char>&]
     operator<<(_Ostream&& __os, const _Tp& __x)
     ^~~~~~~~
***********************

Fortunately 'cam.h' includes an optional no-op implementation of 'StreamCapture' that does compile.  Since
CAM isn't used in OSV, use that no-op version by default.  The existing, unaltered, live version remains and
can be compiled by defining the c++ preprocessor macro 'CAM_EXPLICITLY_ENABLED'.